//--------------------------------------------------
// Enumerations of User Timer Events
//--------------------------------------------------
    _USER_TIMER_EVENT_KEY_REPEAT_ENABLE,
    _USER_TIMER_EVENT_KEY_SCAN_READY,
    _USER_TIMER_EVENT_OSD_DISABLE_OSD_LOGO,
    _USER_TIMER_EVENT_OSD_SHOW_NO_CABLE,
    _USER_TIMER_EVENT_OSD_SHOW_NO_SIGNAL,
    _USER_TIMER_EVENT_OSD_SHOW_POWER_SAVING,
    _USER_TIMER_EVENT_GO_TO_POWER_SAVING,
    _USER_TIMER_EVENT_OSD_DISABLE,
    _USER_TIMER_EVENT_PANEL_BACKLIGHT_ON,
    _USER_TIMER_EVENT_PANEL_POWER_OFF,
    _USER_TIMER_EVENT_DO_AUTO_COLOR,
    _USER_TIMER_EVENT_DO_AUTO_ADJUST,
    _USER_TIMER_EVENT_PANEL_USED_TIMER,

#if(_HIGHLIGHT_WINDOW_SUPPORT == _ON)
    _USER_TIMER_EVENT_HLWIN_TYPE5_MOVE,
#endif

    _USER_TIMER_EVENT_OSD_KEYINFO_UNHIGHLIGHT,
    _USER_TIMER_EVENT_OSD_SHOW_DP_VERSION_SELECT,
    _USER_TIMER_EVENT_OSD_DISPLAYMODE_SELECT,

#if(_FREESYNC_SUPPORT == _ON)
    _USER_TIMER_EVENT_OSD_SHOW_FREESYNC_VFREQ,
#endif

#if(_FREEZE_SUPPORT == _ON)
    _USER_TIMER_EVENT_OSD_DISABLE_FREEZE_MSG,
#endif
#if(_FALSE_COLOR_SUPPORT == _ON)
    _USER_TIMER_EVENT_OSD_DISABLE_FALSE_COLOR_MSG,
#endif
