//--------------------------------------------------
// Enumerations of Scaler Timer Events
//--------------------------------------------------
#if((_DVI_SUPPORT == _ON) || (_HDMI_SUPPORT == _ON))
#if(_D0_TMDS_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX0_TMDS_VIDEO_DETECT,
#if(_D0_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX0_TMDS_HDMI_PACKET_DETECT,
#endif
#endif
#if(_D1_TMDS_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX1_TMDS_VIDEO_DETECT,
#if(_D1_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX1_TMDS_HDMI_PACKET_DETECT,
#endif
#endif
#if(_D2_TMDS_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX2_TMDS_VIDEO_DETECT,
#if(_D2_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX2_TMDS_HDMI_PACKET_DETECT,
#endif
#endif
#if(_D3_TMDS_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX3_TMDS_VIDEO_DETECT,
#if(_D3_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX3_TMDS_HDMI_PACKET_DETECT,
#endif
#endif
#if(_D4_TMDS_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX4_TMDS_VIDEO_DETECT,
#if(_D4_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX4_TMDS_HDMI_PACKET_DETECT,
#endif
#endif
#if(_D5_TMDS_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX5_TMDS_VIDEO_DETECT,
#if(_D5_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX5_TMDS_HDMI_PACKET_DETECT,
#endif
#endif

#if(_HDMI_2_0_SUPPORT == _ON)
#if(_D0_HDMI_2_0_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX0_HDMI2_FORMAT_RESET_WAIT,
#endif
#if(_D1_HDMI_2_0_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX1_HDMI2_FORMAT_RESET_WAIT,
#endif
#if(_D2_HDMI_2_0_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX2_HDMI2_FORMAT_RESET_WAIT,
#endif
#if(_D3_HDMI_2_0_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX3_HDMI2_FORMAT_RESET_WAIT,
#endif
#if(_D4_HDMI_2_0_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX4_HDMI2_FORMAT_RESET_WAIT,
#endif
#if(_D5_HDMI_2_0_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_RX5_HDMI2_FORMAT_RESET_WAIT,
#endif
#endif // #if(_HDMI_2_0_SUPPORT == _ON)
#endif //#if((_DVI_SUPPORT == _ON) || (_HDMI_SUPPORT == _ON))

#if(_HDCP_2_2_SUPPORT == _ON)
#if((_D0_INPUT_PORT_TYPE == _D0_HDMI_PORT) || (_D0_INPUT_PORT_TYPE == _D0_MHL_PORT))
    _SCALER_TIMER_EVENT_RX0_HDCP2_REAUTH,
#endif
#if((_D1_INPUT_PORT_TYPE == _D1_HDMI_PORT) || (_D1_INPUT_PORT_TYPE == _D1_MHL_PORT))
    _SCALER_TIMER_EVENT_RX1_HDCP2_REAUTH,
#endif
#if((_D2_INPUT_PORT_TYPE == _D2_HDMI_PORT) || (_D2_INPUT_PORT_TYPE == _D2_MHL_PORT))
    _SCALER_TIMER_EVENT_RX2_HDCP2_REAUTH,
#endif
#if((_D3_INPUT_PORT_TYPE == _D3_HDMI_PORT) || (_D3_INPUT_PORT_TYPE == _D3_MHL_PORT))
    _SCALER_TIMER_EVENT_RX3_HDCP2_REAUTH,
#endif
#if((_D4_INPUT_PORT_TYPE == _D4_HDMI_PORT) || (_D4_INPUT_PORT_TYPE == _D4_MHL_PORT))
    _SCALER_TIMER_EVENT_RX4_HDCP2_REAUTH,
#endif
#if((_D5_INPUT_PORT_TYPE == _D5_HDMI_PORT) || (_D5_INPUT_PORT_TYPE == _D5_MHL_PORT))
    _SCALER_TIMER_EVENT_RX5_HDCP2_REAUTH,
#endif
#endif

#if(_AUDIO_SUPPORT == _ON)
#if((_D0_HDMI_SUPPORT == _ON) || (_D0_INPUT_PORT_TYPE == _D0_DP_PORT))
    _SCALER_TIMER_EVENT_AUDIO_D0_LOAD_STABLE_I_CODE,
#endif
#if((_D1_HDMI_SUPPORT == _ON) || (_D1_INPUT_PORT_TYPE == _D1_DP_PORT))
    _SCALER_TIMER_EVENT_AUDIO_D1_LOAD_STABLE_I_CODE,
#endif
#if(_D2_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_AUDIO_D2_LOAD_STABLE_I_CODE,
#endif
#if(_D3_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_AUDIO_D3_LOAD_STABLE_I_CODE,
#endif
#if(_D4_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_AUDIO_D4_LOAD_STABLE_I_CODE,
#endif
#if(_D5_HDMI_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_AUDIO_D5_LOAD_STABLE_I_CODE,
#endif
#endif // End of #if(_AUDIO_SUPPORT == _ON)

#if(_DP_SUPPORT == _ON)
#if((_D0_INPUT_PORT_TYPE == _D0_DP_PORT) || (_D6_INPUT_PORT_TYPE != _D6_NO_PORT))
    _SCALER_TIMER_EVENT_DP_RX0_HOTPLUG_ASSERTED,
    _SCALER_TIMER_EVENT_DP_RX0_HDCP_LONG_HOTPLUG_EVENT,
    _SCALER_TIMER_EVENT_DP_RX0_LINK_STATUS_IRQ,
    _SCALER_TIMER_EVENT_DP_RX0_VALID_SIGNAL_DETECT_CHECK,
#if(_ULTRA_HDR_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX0_RSV0_PACKET_DETECT,
#endif
#if((_DP_VSC_SDP_EXT_FOR_COLORIMETRY_SUPPORT == _ON) && (_HW_DP_VSC_SDP_REG_SUPPORT != _ON))
    _SCALER_TIMER_EVENT_DP_RX0_RSV1_PACKET_DETECT,
#endif
#if(_DP_MST_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX0_AUX_CH_NO_POWER_CHECK_DEBOUNCE,
    _SCALER_TIMER_EVENT_DP_RX0_AUX_CH_POWER_ON_WAIT_HOTPLUG_HIGH,
#if(_DP_TX_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX0_HDCP_CPIRQ_EVENT,
    _SCALER_TIMER_EVENT_DP_RX0_HDCP_REPEATER_PROC_TIMEOUT,
    _SCALER_TIMER_EVENT_DP_RX0_HDCP_READ_IRQ_TIMEOUT,
#if((_DP_VSC_SDP_EXT_FOR_COLORIMETRY_SUPPORT == _ON) && (_HW_DP_VSC_SDP_REG_SUPPORT != _ON))
    _SCALER_TIMER_EVENT_DP_RX0_MST2SST_RSV1_PACKET_DETECT,
#endif
#endif
#endif // End of #if(_DP_MST_SUPPORT == _ON)
#endif // End of #if((_D0_INPUT_PORT_TYPE == _D0_DP_PORT) || (_D6_INPUT_PORT_TYPE != _D6_NO_PORT))

#if(_D1_INPUT_PORT_TYPE == _D1_DP_PORT)
    _SCALER_TIMER_EVENT_DP_RX1_HOTPLUG_ASSERTED,
    _SCALER_TIMER_EVENT_DP_RX1_HDCP_LONG_HOTPLUG_EVENT,
    _SCALER_TIMER_EVENT_DP_RX1_LINK_STATUS_IRQ,
    _SCALER_TIMER_EVENT_DP_RX1_VALID_SIGNAL_DETECT_CHECK,
#if(_ULTRA_HDR_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX1_RSV0_PACKET_DETECT,
#endif
#if((_DP_VSC_SDP_EXT_FOR_COLORIMETRY_SUPPORT == _ON) && (_HW_DP_VSC_SDP_REG_SUPPORT != _ON))
    _SCALER_TIMER_EVENT_DP_RX1_RSV1_PACKET_DETECT,
#endif
#if(_DP_MST_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX1_AUX_CH_NO_POWER_CHECK_DEBOUNCE,
    _SCALER_TIMER_EVENT_DP_RX1_AUX_CH_POWER_ON_WAIT_HOTPLUG_HIGH,
#if(_DP_TX_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_RX1_HDCP_CPIRQ_EVENT,
    _SCALER_TIMER_EVENT_DP_RX1_HDCP_REPEATER_PROC_TIMEOUT,
    _SCALER_TIMER_EVENT_DP_RX1_HDCP_READ_IRQ_TIMEOUT,
#if((_DP_VSC_SDP_EXT_FOR_COLORIMETRY_SUPPORT == _ON) && (_HW_DP_VSC_SDP_REG_SUPPORT != _ON))
    _SCALER_TIMER_EVENT_DP_RX1_MST2SST_RSV1_PACKET_DETECT,
#endif
#endif
#endif // End of #if(_DP_MST_SUPPORT == _ON)
#endif // End of #if(_D1_INPUT_PORT_TYPE == _D1_DP_PORT)

#if(_DP_MST_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_MSG_TIMEOUT_EVENT,
#endif // End of #if(_DP_MST_SUPPORT == _ON)
#if(_DP_TX_SUPPORT == _ON)
    _SCALER_TIMER_EVENT_DP_TX_CABLE_STATUS_CHANGE_EVENT,
    _SCALER_TIMER_EVENT_DP_RX_MSG_COUNT_RESET_EVENT,
    _SCALER_TIMER_EVENT_DP_TX_MSG_COUNT_RESET_EVENT,
    _SCALER_TIMER_EVENT_DP_TX_HDCP_WAITING_TO_READ_R0,
    _SCALER_TIMER_EVENT_DP_TX_HDCP_WAITING_FOR_V_READY,
    _SCALER_TIMER_EVENT_DP_TX_HDCP_POLLING_V_READY,
#endif
#endif // End of #if(_DP_SUPPORT == _ON)

    _SCALER_TIMER_EVENT_PHASE_CALIBRATION,
    _SCALER_TIMER_EVENT_PHASE_CNT_CHECK,

#if(_D0_INPUT_PORT_TYPE == _D0_MHL_PORT)
    _SCALER_TIMER_EVENT_MHL_RX0_READY_TO_TRANSMIT,
    _SCALER_TIMER_EVENT_MHL_RX0_RECONNECT_1K,
    _SCALER_TIMER_EVENT_MHL_RX0_SWITCH_PORT_DISCOVERY_DONE,
#if(_D0_MHL_VERSION >= _MHL_VERSION_3_0)
    _SCALER_TIMER_EVENT_MHL3_RX0_WAIT_SRC_MHL_VERSION,
    _SCALER_TIMER_EVENT_MHL3_RX0_WAIT_SRC_RAP_CBUS_UP,
    _SCALER_TIMER_EVENT_MHL3_RX0_WAIT_FWD_CLK,
    _SCALER_TIMER_EVENT_MHL3_RX0_ECBUS_START_UP,
    _SCALER_TIMER_EVENT_MHL3_RX0_ECBUS_BIST_DURATION,
    _SCALER_TIMER_EVENT_MHL3_RX0_AV_LINK_BIST_SET_PHY,
#endif // End of #if(_D0_MHL_VERSION >= _MHL_VERSION_3_0)
#endif // End of #if(_D0_INPUT_PORT_TYPE == _D0_MHL_PORT)
#if(_D1_INPUT_PORT_TYPE == _D1_MHL_PORT)
    _SCALER_TIMER_EVENT_MHL_RX1_READY_TO_TRANSMIT,
    _SCALER_TIMER_EVENT_MHL_RX1_RECONNECT_1K,
    _SCALER_TIMER_EVENT_MHL_RX1_SWITCH_PORT_DISCOVERY_DONE,
#if(_D1_MHL_VERSION >= _MHL_VERSION_3_0)
    _SCALER_TIMER_EVENT_MHL3_RX1_WAIT_SRC_MHL_VERSION,
    _SCALER_TIMER_EVENT_MHL3_RX1_WAIT_SRC_RAP_CBUS_UP,
    _SCALER_TIMER_EVENT_MHL3_RX1_WAIT_FWD_CLK,
    _SCALER_TIMER_EVENT_MHL3_RX1_ECBUS_START_UP,
    _SCALER_TIMER_EVENT_MHL3_RX1_ECBUS_BIST_DURATION,
    _SCALER_TIMER_EVENT_MHL3_RX1_AV_LINK_BIST_SET_PHY,
#endif // End of #if(_D1_MHL_VERSION >= _MHL_VERSION_3_0)
#endif // End of #if(_D1_INPUT_PORT_TYPE == _D1_MHL_PORT)
#if(_D2_INPUT_PORT_TYPE == _D2_MHL_PORT)
    _SCALER_TIMER_EVENT_MHL_RX2_READY_TO_TRANSMIT,
    _SCALER_TIMER_EVENT_MHL_RX2_RECONNECT_1K,
    _SCALER_TIMER_EVENT_MHL_RX2_SWITCH_PORT_DISCOVERY_DONE,
#if(_D2_MHL_VERSION >= _MHL_VERSION_3_0)
    _SCALER_TIMER_EVENT_MHL3_RX2_WAIT_SRC_MHL_VERSION,
    _SCALER_TIMER_EVENT_MHL3_RX2_WAIT_SRC_RAP_CBUS_UP,
    _SCALER_TIMER_EVENT_MHL3_RX2_WAIT_FWD_CLK,
    _SCALER_TIMER_EVENT_MHL3_RX2_ECBUS_START_UP,
    _SCALER_TIMER_EVENT_MHL3_RX2_ECBUS_BIST_DURATION,
    _SCALER_TIMER_EVENT_MHL3_RX2_AV_LINK_BIST_SET_PHY,
#endif // End of #if(_D2_MHL_VERSION >= _MHL_VERSION_3_0)
#endif // End of #if(_D2_INPUT_PORT_TYPE == _D2_MHL_PORT)
#if(_D3_INPUT_PORT_TYPE == _D3_MHL_PORT)
    _SCALER_TIMER_EVENT_MHL_RX3_READY_TO_TRANSMIT,
    _SCALER_TIMER_EVENT_MHL_RX3_RECONNECT_1K,
    _SCALER_TIMER_EVENT_MHL_RX3_SWITCH_PORT_DISCOVERY_DONE,
#if(_D3_MHL_VERSION >= _MHL_VERSION_3_0)
    _SCALER_TIMER_EVENT_MHL3_RX3_WAIT_SRC_MHL_VERSION,
    _SCALER_TIMER_EVENT_MHL3_RX3_WAIT_SRC_RAP_CBUS_UP,
    _SCALER_TIMER_EVENT_MHL3_RX3_WAIT_FWD_CLK,
    _SCALER_TIMER_EVENT_MHL3_RX3_ECBUS_START_UP,
    _SCALER_TIMER_EVENT_MHL3_RX3_ECBUS_BIST_DURATION,
    _SCALER_TIMER_EVENT_MHL3_RX3_AV_LINK_BIST_SET_PHY,
#endif // End of #if(_D3_MHL_VERSION >= _MHL_VERSION_3_0)
#endif // End of #if(_D3_INPUT_PORT_TYPE == _D3_MHL_PORT)
#if(_D4_INPUT_PORT_TYPE == _D4_MHL_PORT)
    _SCALER_TIMER_EVENT_MHL_RX4_READY_TO_TRANSMIT,
    _SCALER_TIMER_EVENT_MHL_RX4_RECONNECT_1K,
    _SCALER_TIMER_EVENT_MHL_RX4_SWITCH_PORT_DISCOVERY_DONE,
#if(_D4_MHL_VERSION >= _MHL_VERSION_3_0)
    _SCALER_TIMER_EVENT_MHL3_RX4_WAIT_SRC_MHL_VERSION,
    _SCALER_TIMER_EVENT_MHL3_RX4_WAIT_SRC_RAP_CBUS_UP,
    _SCALER_TIMER_EVENT_MHL3_RX4_WAIT_FWD_CLK,
    _SCALER_TIMER_EVENT_MHL3_RX4_ECBUS_START_UP,
    _SCALER_TIMER_EVENT_MHL3_RX4_ECBUS_BIST_DURATION,
    _SCALER_TIMER_EVENT_MHL3_RX4_AV_LINK_BIST_SET_PHY,
#endif // End of #if(_D4_MHL_VERSION >= _MHL_VERSION_3_0)
#endif // End of #if(_D4_INPUT_PORT_TYPE == _D4_MHL_PORT)
#if(_D5_INPUT_PORT_TYPE == _D5_MHL_PORT)
    _SCALER_TIMER_EVENT_MHL_RX5_READY_TO_TRANSMIT,
    _SCALER_TIMER_EVENT_MHL_RX5_RECONNECT_1K,
    _SCALER_TIMER_EVENT_MHL_RX5_SWITCH_PORT_DISCOVERY_DONE,
#if(_D5_MHL_VERSION >= _MHL_VERSION_3_0)
    _SCALER_TIMER_EVENT_MHL3_RX5_WAIT_SRC_MHL_VERSION,
    _SCALER_TIMER_EVENT_MHL3_RX5_WAIT_SRC_RAP_CBUS_UP,
    _SCALER_TIMER_EVENT_MHL3_RX5_WAIT_FWD_CLK,
    _SCALER_TIMER_EVENT_MHL3_RX5_ECBUS_START_UP,
    _SCALER_TIMER_EVENT_MHL3_RX5_ECBUS_BIST_DURATION,
    _SCALER_TIMER_EVENT_MHL3_RX5_AV_LINK_BIST_SET_PHY,
#endif // End of #if(_D5_MHL_VERSION >= _MHL_VERSION_3_0)
#endif // End of #if(_D5_INPUT_PORT_TYPE == _D5_MHL_PORT)
