//--------------------------------------------------
// Enumerations of System Timer Events
//--------------------------------------------------
    _SYSTEM_TIMER_EVENT_SOURCE_CLEAR_DETECTING,
    _SYSTEM_TIMER_EVENT_JUDGE_ACTIVE_STATE,
    _SYSTEM_TIMER_EVENT_JUDGE_NOSUPPORT_STATE,
    _SYSTEM_TIMER_EVENT_SOURCE_NOSUPPORT_STATE,
    _SYSTEM_TIMER_EVENT_SOURCE_NOSIGNAL_STATE,

#if((_D6_INPUT_PORT_TYPE != _D6_NO_PORT) && (_D6_INPUT_PORT_SWITCH_FROM == _SWITCH_FROM_D0))
    _SYSTEM_TIMER_EVENT_SOURCE_DP_SWITCH_TIMEOUT,
#endif

#if(_D7_INPUT_PORT_TYPE != _D7_NO_PORT)
    _SYSTEM_TIMER_EVENT_SOURCE_DP_DUAL_SWITCH_TIMEOUT,
#endif

#if(_EMBEDDED_DAC_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_AUDIO_DAC_WAIT_VCM_INITIAL,
    _SYSTEM_TIMER_EVENT_AUDIO_DAC_WAIT_VCM_CHARGE,
    _SYSTEM_TIMER_EVENT_AUDIO_DAC_WAIT_DEPOP_TO_NORMAL,
#endif

#if(_D0_DP_TYPE_C_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D0_TYPEC_CABLE_DETECT,
#if(_D0_DP_USB_HUB_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D0_USBHUB_DETECT,
#endif
#endif

#if(_D1_DP_TYPE_C_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D1_TYPEC_CABLE_DETECT,
#if(_D1_DP_USB_HUB_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D1_USBHUB_DETECT,
#endif
#endif

#if(_D6_DP_TYPE_C_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D6_TYPEC_CABLE_DETECT,
#if(_D6_DP_USB_HUB_SUPPORT == _ON)
    _SYSTEM_TIMER_EVENT_D6_USBHUB_DETECT,
#endif
#endif
